# Site settings
title: "Las Tierras Land Investments"
description: "Affordable 5-Acre Ranches in Brownsville, TX"
baseurl: "" # Set this to "/repository-name" if your site is in a subdirectory
url: "https://joseg35.github.io/Las-tierras-website" # Replace with your GitHub Pages URL

# Theme settings
theme: jekyll-theme-cayman@v0.2.0

# Optional site details
author: "Las Tierras Land Investments"
email: "your-email@example.com" # Replace with your contact email
social_links:
  github: "https://github.com/joseg35"
  linkedin: "https://www.linkedin.com/in/your-profile/" # Replace with your LinkedIn URL
  facebook: "https://www.facebook.com/your-page/" # Replace with your Facebook page URL

# Plugins (Optional for extra features)
plugins:
  - jekyll-seo-tag # Adds SEO optimization
  - jekyll-sitemap # Automatically generates a sitemap
  - jekyll-feed # Adds an RSS feed for blog posts

# Customization options (if needed)
permalink: pretty # Clean URLs for your site
markdown: kramdown # Markdown engine for Jekyll
highlighter: rouge # Code highlighting for posts or pages